In [2]:
import pandas as pd
from pathlib import Path

In [3]:
DATA_PATH=Path().cwd()/"data"/"raw"
print(DATA_PATH)

c:\Users\Mi PC\Desktop\liger_coffee_shop\data\raw

In [4]:
tablas = {
    "branches": None,
    "ingredients": None,
    "inventory_movements": None,
    "order_items": None,
    "orders": None,
    "products": None,
    "purchases": None,
    "recipes": None
}

for item in tablas:
    df = pd.read_csv(f"{DATA_PATH}/{item}.csv")
    column_names = df.columns.tolist()
    tablas[item] = column_names

C:\Users\Mi PC\AppData\Local\Temp\ipykernel_13504\215503434.py:13: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"{DATA_PATH}/{item}.csv")

In [5]:
tablas

{'branches': ['branch_id', 'name'],
 'ingredients': ['ingredient_id',
  'name',
  'unit_of_measure',
  'unit_cost',
  'category'],
 'inventory_movements': ['movement_id',
  'ingredient_id',
  'movement_type',
  'quantity',
  'order_item_id',
  'purchase_id',
  'occurred_at',
  'notes'],
 'order_items': ['order_item_id',
  'order_id',
  'product_id',
  'quantity',
  'sale_price'],
 'orders': ['order_id',
  'branch_id',
  'created_at',
  'in_or_out',
  'payment_method'],
 'products': ['product_id', 'name', 'category', 'unit_price'],
 'purchases': ['purchase_id',
  'ingredient_id',
  'branch_id',
  'quantity',
  'unit_cost_real',
  'supplier_name',
  'purchased_at'],
 'recipes': ['recipe_id', 'product_id', 'ingredient_id', 'quantity_required']}

In [6]:
order_items=pd.read_csv(f"{DATA_PATH}/order_items.csv")

In [7]:
order_items["order_id"].head()

0    1
1    1
2    2
3    3
4    4
Name: order_id, dtype: int64

In [8]:
order_items["order_id"].duplicated().sum()

23657

In [9]:
orders=pd.read_csv(f"{DATA_PATH}/orders.csv")

In [10]:
orders["in_or_out"].unique()

array(['takeout', 'dine_in'], dtype=object)

In [11]:
recipes=pd.read_csv(f"{DATA_PATH}/recipes.csv")
recipes.head()

   recipe_id  product_id  ingredient_id  quantity_required
0          1           1              1              0.018
1          2           1              2              0.150
2          3           1             15              1.000
3          4           2              1              0.018
4          5           2              2              0.120

In [13]:
products=pd.read_csv(f"{DATA_PATH}/products.csv")
products.head()

   product_id                name         category  unit_price
0           1      Latte caliente  bebida_caliente        55.0
1           2          Cappuccino  bebida_caliente        52.0
2           3      Café americano  bebida_caliente        38.0
3           4  Chocolate caliente  bebida_caliente        50.0
4           5         Té caliente  bebida_caliente        35.0

In [16]:
purchases=pd.read_csv(f"{DATA_PATH}/purchases.csv")
purchases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3780 entries, 0 to 3779
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   purchase_id     3780 non-null   int64
 1   ingredient_id   3780 non-null   int64
 2   branch_id       3780 non-null   int64
 3   quantity        3780 non-null   float64
 4   unit_cost_real  3780 non-null   float64
 5   supplier_name   3780 non-null   object
 6   purchased_at    3780 non-null   object
dtypes: float64(2), int64(3), object(2)
memory usage: 206.8+ KB

In [17]:
orders.head()

   order_id  branch_id           created_at in_or_out payment_method
0         1          1  2024-09-01 17:05:00   takeout           cash
1         2          1  2024-09-01 18:41:00   takeout           card
2         3          1  2024-09-01 08:51:00   takeout           card
3         4          1  2024-09-01 17:49:00   dine_in           cash
4         5          1  2024-09-01 16:21:00   dine_in           cash

In [18]:
orders["in_or_out"]=orders["in_or_out"].replace("takeout", "take_out")
orders.to_csv("orders.csv", index=False)

In [19]:
orders.head()

   order_id  branch_id           created_at in_or_out payment_method
0         1          1  2024-09-01 17:05:00  take_out           cash
1         2          1  2024-09-01 18:41:00  take_out           card
2         3          1  2024-09-01 08:51:00  take_out           card
3         4          1  2024-09-01 17:49:00   dine_in           cash
4         5          1  2024-09-01 16:21:00   dine_in           cash

In [ ]:
C:\Users\Mi PC\Desktop\liger_coffee_shop\data\raw\processed